import Image from "next/image"
import { ArrowDownRight, ArrowUpRight, Check, Clock3, Phone, ShieldCheck, MessageCircle, Wrench, Asterisk } from "lucide-react"
import { Brand, LegalLinks, ScheduleButton } from "@/components/site-shell"

export function ComfortStory() {
  return <><section id="comfort-story" className="comfort-story section-pad"><div className="story-top" data-reveal><p className="eyebrow">YOU DON’T THINK ABOUT YOUR AIR.</p><span className="story-line" /></div><div className="story-main" data-reveal><h2>Until it<br /><span>doesn&apos;t.</span></h2><div className="story-details"><p className="story-statement">An AC that stops working<br />doesn&apos;t care what time it is.</p><p>Or how hot it is outside. Or that you finally have a quiet evening at home. When something feels off, you deserve a straightforward way forward.</p><div className="problem-list"><span>Air that isn&apos;t cool.</span><span>A furnace that won&apos;t start.</span><span>A noise you haven&apos;t heard before.</span><span>A leak. A hot room. An unexpected breakdown.</span></div></div></div><div className="story-resolution" data-reveal><span className="resolution-icon"><ArrowDownRight size={32} strokeWidth={1.3} /></span><p>That&apos;s where <span>we come in.</span></p><span className="eyebrow">LESS WORRY. MORE COMFORT.</span></div></section>
  <section className="fast-response section-pad" id="why-northstar"><div className="response-heading" data-reveal><div><p className="eyebrow">THE HELP YOU NEED. WITHOUT THE RUNAROUND.</p><h2>Comfort shouldn&apos;t<br />have to wait.</h2></div><div><p>When your system fails, you need a real person, a clear answer, and a technician who knows what they&apos;re doing.</p><ScheduleButton service="Emergency Service">Get Help Now</ScheduleButton></div></div><div className="response-benefits" data-reveal>{[{ icon: Clock3, title: "Same-day service", text: "Because your day shouldn’t revolve around a broken system." }, { icon: Phone, title: "Here for the unexpected", text: "24/7 emergency HVAC service when tomorrow is too far away." }, { icon: ShieldCheck, title: "Expertise you can trust", text: "Licensed, experienced technicians who respect your home.*" }, { icon: MessageCircle, title: "No surprises", text: "Clear options and upfront communication. From the first call." }].map(({ icon: Icon, title, text }) => <div key={title}><Icon size={25} strokeWidth={1.4} /><h3>{title}</h3><p>{text}</p></div>)}</div><p className="fine-print response-disclaimer">*Service availability and credentials are illustrative for this fictional brand.</p></section></>
}
const steps = [
  ["Understand", "We learn how your home behaves, what you’re experiencing, and what your current system is doing."],
  ["Recommend", "We explain your options clearly — without pushing what you don’t need."],
  ["Solve", "Our technicians install, repair, or maintain your system properly. The details matter."],
  ["Follow through", "We don’t disappear after the job is done. Your comfort is an ongoing conversation."],
]
export function Approach() {
  return <section className="approach section-pad"><div className="approach-image" data-reveal><Image src="/images/technician.png" alt="A technician thoughtfully inspecting a home’s air conditioning equipment" fill sizes="(max-width: 760px) 100vw, 45vw" /><div className="image-note"><Asterisk size={28} strokeWidth={1.3} /><span>YOUR HOME ISN’T ONE-SIZE-FITS-ALL.<br />YOUR SERVICE SHOULDN’T BE EITHER.</span></div></div><div className="approach-copy" data-reveal><p className="eyebrow">BUILT AROUND YOUR HOME</p><h2>The right system<br />starts with the right<br />understanding.</h2><div className="process-steps">{steps.map(([title, copy], index) => <div className="process-step" key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></section>
}
export function People() {
  return <section id="about" className="people section-pad"><div className="section-heading" data-reveal><div><p className="eyebrow">REAL PEOPLE. REAL PEACE OF MIND.</p><h2>Good service starts<br />with good people.</h2></div><p>The person at your door matters.<br />So does the way they treat your home.</p></div><div className="people-image" data-reveal><Image src="/images/team.png" alt="Two Northstar demonstration technicians discussing a job outside a North Texas home" fill sizes="100vw" /><div className="people-note"><p>Professional in our work.<br />Neighborly in everything else.</p><span>THAT’S THE NORTHSTAR WAY.</span></div></div><div className="people-qualities">{["Licensed technicians*", "Background checked*", "Experienced", "Locally focused", "Respectful of your home"].map(text => <span key={text}><Check size={17} />{text}</span>)}</div><p className="fine-print">*Illustrative team standards, not verified credentials. People shown are AI-generated.</p></section>
}
export function Financing() {
  return <section className="financing section-pad" data-reveal><div className="financing-title"><p className="eyebrow">MORE COMFORT. LESS PRESSURE.</p><h2>A better system shouldn&apos;t<br />mean a stressful decision.</h2></div><div><p>Flexible financing options may be available for qualifying homeowners. Let&apos;s start with what works for you.</p><ScheduleButton service="AC Installation" variant="outline">Explore Your Options</ScheduleButton><p className="fine-print">Subject to eligibility and terms. No financing offered in this demo.</p></div></section>
}
export function FinalCTA() {
  return <section className="final-cta"><Image src="/images/evening-home.png" alt="A peaceful, warmly lit living room at the end of the day" fill sizes="100vw" /><div className="final-shade" /><div className="final-content" data-reveal><p className="eyebrow">BACK TO WHAT HOME SHOULD FEEL LIKE.</p><h2>Let&apos;s get your home<br />comfortable again.</h2><p>Whether your AC stopped working, your furnace needs attention,<br className="desktop-break" /> or you&apos;re ready for a better system, we&apos;re ready to help.</p><div className="hero-actions"><ScheduleButton /><a href="tel:+12145550147" className="hero-call"><Phone size={17} />Call (214) 555-0147</a></div></div></section>
}
export function Footer() {
  return <footer className="site-footer"><div className="footer-main"><div className="footer-brand"><Brand light /><p>Comfort, when you need it most.</p><span>Rooted in Dallas–Fort Worth.<br />Built around your home.</span></div><div className="footer-column"><h3>EXPLORE</h3><a href="#why-northstar">Why Northstar</a><a href="#about">Our people</a><a href="#reviews">Homeowner stories</a><a href="#service-areas">Service areas</a><a href="#faq">Common questions</a></div><div className="footer-column"><h3>HOME COMFORT</h3><a href="#services">AC repair & installation</a><a href="#services">Heating & furnace</a><a href="#services">HVAC maintenance</a><a href="#services">Indoor air quality</a><a href="#why-northstar">Emergency service</a></div><div className="footer-column footer-contact"><h3>LET’S TALK COMFORT</h3><a className="footer-phone" href="tel:+12145550147">(214) 555-0147<ArrowUpRight size={18} /></a><p>Dallas–Fort Worth, Texas</p><p>Appointments by request<br />24/7 emergency service*</p><ScheduleButton variant="link">Schedule Service</ScheduleButton></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Northstar Heating & Air.</span><p>Fictional brand. Real design possibilities.<br /><span>Demo claims, reviews, service hours, and phone number are illustrative.</span></p><LegalLinks /></div></footer>
}
